---
title: "thompson-ryan-ADA-homework-1"
author: "KRT"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Challenge 1

```{r quote}
library(tidyverse)

quote <- "There is grandeur in this view of life,
with its several powers, having been originally breathed
by the Creator into a few forms or into one; and that, whilst
this planet has gone circling on according to the fixed law
of gravity, from so simple a beginning endless forms most
beautiful and most wonderful have been, and are being evolved."

quote2 <- gsub("[[:punct:]]", "", quote)
quote2 <- gsub("\n", " ", quote2)

split_quote <- str_split(quote2, pattern = fixed(" "))
split_quote2 <- unlist(split_quote)
split_quote2

every_fourth <- split_quote2[seq(from = 4, to = 65, by = 4)]
every_fourth

sort(every_fourth, decreasing = TRUE)
```

# Challenge 2

```{r matrix}

m1 <- matrix (data = seq(1, 160, 2), 
             nrow = 8, 
             ncol = 10)
m1

(m1[5, 2]) 
(m1[5:7,])

m2 <- m1[3:6, 4:9]
class(m2)
mode(m2)
```

# Challenge 3

```{r array}
a <- array (data = 400:1,
            dim = c(5, 5, 4, 4))
a

a[1, 1, 1, 2]
a[2, 3, 2, ]
a[1:5, 1:5, 3, 3]
```

#Challenge 4

```{r listception}
primates <- list (
  strepsirhini <- list(
    lorisiformes <- list(
      lorisoidea <- c(
        "lorisidae", "galagidae"
      )
    ),
    lemuriformes <- list(
      lemuroidea <- c(
        "lemuroidea", "cheirogaleidae", "indriidae", "lemuridae", "daubentoniidae"
      )
    )
  ),
  haplorhini <- list(
    tarsliformes <- list(
      tarsioidea <- c(
        "tarsiidae"
      )
    ),
    simiiformes <- list(
      platyrrhini <- list(
        ceboidea <- c(
          "cebidae", "atelidae", "pitheciidae"
        )
      ),
      catarrhini <- list(
        hominoidea <- c(
          "hylobatidae", "hominidae"
        ),
        copithecoidea <- c(
          "cercopithecidae"
        )
      )
    )
  )
)
names(tarsliformes) <- c("tarsioidea")

nwm <- primates[[2]][[2]][[1]]
class(nwm)
mode(nwm)

tarsliformes$tarsioidea
```